name: Example Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  show-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current branch
        run: | 
          echo "Event Name: ${{github.event_name}}"
          git branch
          git log